/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * skillParticuleWND.java
 *
 * Created on Jan 4, 2010, 5:20:42 PM
 */
package rifttest.resources;

import org.w3c.dom.Element;
import rifttest.SkillHandler;

/**
 *
 * @author Maude
 */
public class skillParticuleWND extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private Element e;
    private int type;
    private SkillHandler handler;
    public static final int AWARD = 0;
    public static final int ABILITY = 1;
    public static final int BONUS = 2;
    public static final int RESTRICTION = 3;

    /** Creates new form skillParticuleWND */
    public skillParticuleWND(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tag1 = new javax.swing.JLabel();
        box1 = new javax.swing.JTextField();
        tag2 = new javax.swing.JLabel();
        box2 = new javax.swing.JTextField();
        tag3 = new javax.swing.JLabel();
        box3 = new javax.swing.JTextField();
        tag4 = new javax.swing.JLabel();
        box4 = new javax.swing.JTextField();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rifttest.RiftTestApp.class).getContext().getResourceMap(skillParticuleWND.class);
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        tag1.setText(resourceMap.getString("tag1.text")); // NOI18N
        tag1.setName("tag1"); // NOI18N

        box1.setText(resourceMap.getString("box1.text")); // NOI18N
        box1.setName("box1"); // NOI18N

        tag2.setText(resourceMap.getString("tag2.text")); // NOI18N
        tag2.setName("tag2"); // NOI18N

        box2.setText(resourceMap.getString("box2.text")); // NOI18N
        box2.setName("box2"); // NOI18N

        tag3.setText(resourceMap.getString("tag3.text")); // NOI18N
        tag3.setName("tag3"); // NOI18N

        box3.setText(resourceMap.getString("box3.text")); // NOI18N
        box3.setName("box3"); // NOI18N

        tag4.setText(resourceMap.getString("tag4.text")); // NOI18N
        tag4.setName("tag4"); // NOI18N

        box4.setText(resourceMap.getString("box4.text")); // NOI18N
        box4.setName("box4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tag1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tag2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tag3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tag4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(box4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tag1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tag2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tag3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tag4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        switch (type) {
            case 0:
                e.setAttribute("name", box1.getText());
                e.setAttribute("base", box2.getText());
                e.setAttribute("onLevel", box3.getText());
                break;
            case 1:
                e.setAttribute("name", box1.getText());
                e.setAttribute("bonus", box2.getText());
                e.setAttribute("altSkill", box3.getText());
                e.setAttribute("altBonus", box4.getText());
                break;
            case 2:
                //if(box2.getText().equalsIgnoreCase("") ^ box3.getText().equalsIgnoreCase("")){
                e.setAttribute("target", box1.getText());
                e.setAttribute("amount", box2.getText());
                e.setAttribute("roll", box3.getText());
                //}
                break;
            case 3:
                e.setAttribute("name", box1.getText());
                e.setAttribute("type", box2.getText());
                e.setAttribute("bonus", box3.getText());
                break;
        }
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                skillParticuleWND dialog = new skillParticuleWND(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JTextField box4;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel tag1;
    private javax.swing.JLabel tag2;
    private javax.swing.JLabel tag3;
    private javax.swing.JLabel tag4;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    public Element retElement() {
        return e;
    }

    public void setData(Element elem, int _type, SkillHandler H) {
        e = elem;
        type = _type;
        handler = H;
        switch (type) {
            case 0:
                // set lables
                tag1.setText("Name");
                tag2.setText("Base skill level");
                tag3.setText("on level up");
                tag4.setText("Not Used");
                box4.setEnabled(false);
                // fill boxs
                box1.setText(elem.getAttribute("name"));
                box2.setText(elem.getAttribute("base"));
                box3.setText(elem.getAttribute("onLevel"));
                break;
            case 1:
                tag1.setText("Name");
                tag2.setText("Bonus");
                tag3.setText("Alternative");
                tag4.setText("Bonus");
                box1.setText(elem.getAttribute("name"));
                box2.setText(elem.getAttribute("bonus"));
                box3.setText(elem.getAttribute("altSkill"));
                box4.setText(elem.getAttribute("altBonus"));
                break;
            case 2:
                tag1.setText("Targeted stat");
                tag2.setText("buns amount");
                tag3.setText("or Die roll");
                tag4.setText("Not Used");
                box4.setEnabled(false);
                box1.setText(elem.getAttribute("target"));
                box2.setText(elem.getAttribute("amount"));
                box3.setText(elem.getAttribute("roll"));
                break;
            case 3:
                tag1.setText("Name od skill required");
                tag2.setText("Type of req");
                tag3.setText("Bonus / penality");
                tag4.setText("Not Used");
                box4.setEnabled(false);
                box1.setText(elem.getAttribute("name"));
                box2.setText(elem.getAttribute("type"));
                box3.setText(elem.getAttribute("bonus"));
                break;
        }
    }
}
