/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PowerArmorView.java
 *
 * Created on Jan 6, 2010, 5:32:18 PM
 */
package rifttest;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pascale
 */
public class PowerArmorView extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private Vector vec = new Vector();
    private Vector mdcVec = new Vector();
    private Vector weapVec = new Vector();

    /** Creates new form PowerArmorView */
    public PowerArmorView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        vec = new Vector();
        vec.add(box1);
        vec.add(box2);
        vec.add(box3);
        vec.add(box4);
        vec.add(locationList);
        vec.add(box6);
        vec.add(box7);
        vec.add(weaponsList);
        vec.add(box9);
        vec.add(box10);
        vec.add(box11);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        box1 = new javax.swing.JTextField();
        box2 = new javax.swing.JTextField();
        box3 = new javax.swing.JTextField();
        box4 = new javax.swing.JTextField();
        box6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        weaponsList = new javax.swing.JList();
        box10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        box9 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        box7 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        box11 = new javax.swing.JTextField();
        newWeaponButton = new javax.swing.JButton();
        deleteWeaponButton = new javax.swing.JButton();
        newLocationButton = new javax.swing.JButton();
        deleteLocationButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Model");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Class");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("M.D.C. by Location");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Crew");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("speed");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Weapons System");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Cost");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("Description");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("statisticalData");
        jLabel10.setName("jLabel10"); // NOI18N

        box1.setName("box1"); // NOI18N

        box2.setName("box2"); // NOI18N

        box3.setName("box3"); // NOI18N

        box4.setName("box4"); // NOI18N

        box6.setName("box6"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        locationList.setName("locationList"); // NOI18N
        jScrollPane1.setViewportView(locationList);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        weaponsList.setName("weaponsList"); // NOI18N
        jScrollPane2.setViewportView(weaponsList);

        box10.setName("box10"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        box9.setColumns(20);
        box9.setRows(5);
        box9.setName("box9"); // NOI18N
        jScrollPane3.setViewportView(box9);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        box7.setColumns(20);
        box7.setRows(5);
        box7.setName("box7"); // NOI18N
        jScrollPane4.setViewportView(box7);

        jLabel11.setText("reference");
        jLabel11.setName("jLabel11"); // NOI18N

        box11.setName("box11"); // NOI18N

        newWeaponButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        newWeaponButton.setText("New");
        newWeaponButton.setName("newWeaponButton"); // NOI18N
        newWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWeaponButtonActionPerformed(evt);
            }
        });

        deleteWeaponButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        deleteWeaponButton.setText("Delete");
        deleteWeaponButton.setName("deleteWeaponButton"); // NOI18N
        deleteWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWeaponButtonActionPerformed(evt);
            }
        });

        newLocationButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        newLocationButton.setText("New");
        newLocationButton.setName("newLocationButton"); // NOI18N
        newLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationButtonActionPerformed(evt);
            }
        });

        deleteLocationButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        deleteLocationButton.setText("Delete");
        deleteLocationButton.setName("deleteLocationButton"); // NOI18N
        deleteLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box11, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newLocationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLocationButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(newWeaponButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteWeaponButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addContainerGap(397, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(412, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(deleteWeaponButton)
                    .addComponent(newLocationButton)
                    .addComponent(deleteLocationButton)
                    .addComponent(newWeaponButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void newWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWeaponButtonActionPerformed
        // TODO add your handling code here:
        InputBox wnd = new InputBox(null, true, "Enter new Weapon System:");
        wnd.setVisible(true);
        if (wnd.getReturnStatus() == InputBox.RET_OK) {
            weapVec.add(wnd.getReturnValue());
            weaponsList.setListData(weapVec);
        }
    }//GEN-LAST:event_newWeaponButtonActionPerformed

    private void newLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationButtonActionPerformed
        InputBox wnd = new InputBox(null, true, "Enter new MDC location:");
        wnd.setVisible(true);
        if (wnd.getReturnStatus() == InputBox.RET_OK) {
            mdcVec.add(wnd.getReturnValue());
            locationList.setListData(mdcVec);
        }

    }//GEN-LAST:event_newLocationButtonActionPerformed

    private void deleteLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocationButtonActionPerformed
        // TODO add your handling code here:
        if (mdcVec.size() > 0) {
            mdcVec.remove(locationList.getSelectedIndex());
            locationList.setListData(mdcVec);
        }
    }//GEN-LAST:event_deleteLocationButtonActionPerformed

    private void deleteWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWeaponButtonActionPerformed
        // TODO add your handling code here:
        if (weapVec.size() > 0) {
            weapVec.remove(weaponsList.getSelectedIndex());
            weaponsList.setListData(weapVec);
        }
    }//GEN-LAST:event_deleteWeaponButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PowerArmorView dialog = new PowerArmorView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box10;
    private javax.swing.JTextField box11;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JTextField box4;
    private javax.swing.JTextField box6;
    private javax.swing.JTextArea box7;
    private javax.swing.JTextArea box9;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteLocationButton;
    private javax.swing.JButton deleteWeaponButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList locationList;
    private javax.swing.JButton newLocationButton;
    private javax.swing.JButton newWeaponButton;
    private javax.swing.JButton okButton;
    private javax.swing.JList weaponsList;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    public void setData(ArrayList list) {
        if (list != null) {
            for (int i = 0; i < list.size(); i++) {
                if (i == 4 || i == 7) {
                    // mdc location                                        
                    if (i == 4) {
                        JList f = (JList) vec.get(i);
                        ArrayList l = (ArrayList) list.get(i);
                        for (int x = 0; x < l.size();x++) {
                            mdcVec.add(l.get(x));
                        }
                        f.setListData(l.toArray());
                    } else {
                        JList f = (JList) vec.get(i);
                        ArrayList l = (ArrayList) list.get(i);
                        for (int x = 0; x < l.size();x++) {
                            weapVec.add(l.get(x));
                        }
                        f.setListData(l.toArray());
                    }
                } else if (i == 6 || i == 8) {
                    JTextArea f = (JTextArea) vec.get(i);
                    f.setText((String) list.get(i));
                } else {
                    JTextField f = (JTextField) vec.get(i);
                    f.setText((String) list.get(i));
                }
            }
        }
    }

    public ArrayList getData() {
        ArrayList list = new ArrayList();

        for (int i = 0; i < vec.size(); i++) {
            if (i == 4 || i == 7) {
                if (i == 4) {
                    ArrayList list2 = new ArrayList();
                    for (int x = 0; x < mdcVec.size(); x++) {
                        list2.add(mdcVec.get(x));
                    }
                    list.add(list2);
                } else {
                    ArrayList list2 = new ArrayList();
                    for (int x = 0; x < weapVec.size(); x++) {
                        list2.add(weapVec.get(x));
                    }
                    list.add(list2);
                }
            } else if (i == 6 || i == 8) {
                JTextArea f = (JTextArea) vec.get(i);
                list.add(f.getText());
            } else {
                JTextField f = (JTextField) vec.get(i);
                list.add(f.getText());
            }
        }

        return list;
    }
}
