/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VehiculeView.java
 *
 * Created on Jan 6, 2010, 5:32:36 PM
 */
package rifttest;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pascale
 */
public class VehiculeView extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    Vector vec;
    Vector mdcVec;
    Vector weapVec;

    /** Creates new form VehiculeView */
    public VehiculeView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mdcVec = new Vector();
        weapVec = new Vector();
        vec = new Vector();
        vec.add(box1);
        vec.add(box2);
        vec.add(box3);
        vec.add(box4);
        vec.add(box5);
        vec.add(locationList);
        vec.add(box7);
        vec.add(weaponList);
        vec.add(box9);
        vec.add(box10);
        vec.add(box11);

    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        box1 = new javax.swing.JTextField();
        box2 = new javax.swing.JTextField();
        box3 = new javax.swing.JTextField();
        box4 = new javax.swing.JTextField();
        box5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        box7 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        box9 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        weaponList = new javax.swing.JList();
        box10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        box11 = new javax.swing.JTextField();
        newLocationButton = new javax.swing.JButton();
        editLocationButton = new javax.swing.JButton();
        deleteLocationButton = new javax.swing.JButton();
        newWeaponButton = new javax.swing.JButton();
        editWeaponButton = new javax.swing.JButton();
        deleteWeaponButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Model");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Crew");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Speed");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("MaxRange");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cost");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel8.setText("Statistical Data");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("M.D.C. by location");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Weapons System");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Description");
        jLabel11.setName("jLabel11"); // NOI18N

        box1.setText("jTextField1");
        box1.setName("box1"); // NOI18N

        box2.setText("jTextField2");
        box2.setName("box2"); // NOI18N

        box3.setText("jTextField3");
        box3.setName("box3"); // NOI18N

        box4.setText("jTextField4");
        box4.setName("box4"); // NOI18N

        box5.setText("jTextField5");
        box5.setName("box5"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        box7.setColumns(20);
        box7.setRows(5);
        box7.setText("Please edit description with text from Rift RPG game");
        box7.setName("box7"); // NOI18N
        jScrollPane1.setViewportView(box7);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        locationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        locationList.setName("locationList"); // NOI18N
        jScrollPane2.setViewportView(locationList);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        box9.setColumns(20);
        box9.setRows(5);
        box9.setText("Please edit description with text from Rift RPG game");
        box9.setName("box9"); // NOI18N
        jScrollPane3.setViewportView(box9);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        weaponList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        weaponList.setName("weaponList"); // NOI18N
        jScrollPane4.setViewportView(weaponList);

        box10.setText("jTextField6");
        box10.setName("box10"); // NOI18N

        jLabel7.setText("Ref.");
        jLabel7.setName("jLabel7"); // NOI18N

        box11.setText("jTextField7");
        box11.setName("box11"); // NOI18N

        newLocationButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        newLocationButton.setText("New");
        newLocationButton.setName("newLocationButton"); // NOI18N
        newLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationButtonActionPerformed(evt);
            }
        });

        editLocationButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        editLocationButton.setText("Edit");
        editLocationButton.setName("editLocationButton"); // NOI18N
        editLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLocationButtonActionPerformed(evt);
            }
        });

        deleteLocationButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        deleteLocationButton.setText("Delete");
        deleteLocationButton.setName("deleteLocationButton"); // NOI18N
        deleteLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocationButtonActionPerformed(evt);
            }
        });

        newWeaponButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        newWeaponButton.setText("New");
        newWeaponButton.setName("newWeaponButton"); // NOI18N
        newWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWeaponButtonActionPerformed(evt);
            }
        });

        editWeaponButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        editWeaponButton.setText("Edit");
        editWeaponButton.setName("editWeaponButton"); // NOI18N
        editWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWeaponButtonActionPerformed(evt);
            }
        });

        deleteWeaponButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        deleteWeaponButton.setText("Delete");
        deleteWeaponButton.setName("deleteWeaponButton"); // NOI18N
        deleteWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWeaponButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box5)
                                    .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(box10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(newLocationButton)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(55, 55, 55)
                                                    .addComponent(editLocationButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(deleteLocationButton)))
                                            .addGap(18, 18, 18)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(newWeaponButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(editWeaponButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(deleteWeaponButton))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(newLocationButton)
                        .addComponent(editLocationButton)
                        .addComponent(deleteLocationButton)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newWeaponButton)
                        .addComponent(editWeaponButton)
                        .addComponent(deleteWeaponButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void newLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationButtonActionPerformed
        // TODO add your handling code here:
        InputBox wnd = new InputBox(null, true, "Enter M.D.C Location info:");
        wnd.setVisible(true);
        if(wnd.getReturnStatus() == InputBox.RET_OK){
            mdcVec.add(wnd.getReturnValue());
        }
        locationList.setListData(mdcVec);
    }//GEN-LAST:event_newLocationButtonActionPerformed

    private void editLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLocationButtonActionPerformed
        InputBox wnd = new InputBox(null, true, "Enter M.D.C Location info:");
        wnd.setTextBox((String) mdcVec.get(locationList.getSelectedIndex()));
        wnd.setVisible(true);
        if(wnd.getReturnStatus() == InputBox.RET_OK){
            mdcVec.remove(locationList.getSelectedIndex());
            mdcVec.add(locationList.getSelectedIndex(),wnd.getReturnValue());
        }
        locationList.setListData(mdcVec);
    }//GEN-LAST:event_editLocationButtonActionPerformed

    private void deleteLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocationButtonActionPerformed
        mdcVec.remove(locationList.getSelectedIndex());
        locationList.setListData(mdcVec);
    }//GEN-LAST:event_deleteLocationButtonActionPerformed

    private void editWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWeaponButtonActionPerformed
        InputBox wnd = new InputBox(null, true, "Enter Weapon info:");
        wnd.setTextBox((String) weapVec.get(weaponList.getSelectedIndex()));
        wnd.setVisible(true);
        if(wnd.getReturnStatus() == InputBox.RET_OK){
            weapVec.remove(weaponList.getSelectedIndex());
            weapVec.add(weaponList.getSelectedIndex(),wnd.getReturnValue());
        }
        weaponList.setListData(weapVec);
    }//GEN-LAST:event_editWeaponButtonActionPerformed

    private void deleteWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWeaponButtonActionPerformed
        weapVec.remove(weaponList.getSelectedIndex());
        weaponList.setListData(weapVec);
    }//GEN-LAST:event_deleteWeaponButtonActionPerformed

    private void newWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWeaponButtonActionPerformed
        InputBox wnd = new InputBox(null, true, "Enter Weapon info:");
        wnd.setVisible(true);
        if(wnd.getReturnStatus() == InputBox.RET_OK){
            weapVec.add(wnd.getReturnValue());
        }
        weaponList.setListData(weapVec);
    }//GEN-LAST:event_newWeaponButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                VehiculeView dialog = new VehiculeView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box10;
    private javax.swing.JTextField box11;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JTextField box4;
    private javax.swing.JTextField box5;
    private javax.swing.JTextArea box7;
    private javax.swing.JTextArea box9;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteLocationButton;
    private javax.swing.JButton deleteWeaponButton;
    private javax.swing.JButton editLocationButton;
    private javax.swing.JButton editWeaponButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList locationList;
    private javax.swing.JButton newLocationButton;
    private javax.swing.JButton newWeaponButton;
    private javax.swing.JButton okButton;
    private javax.swing.JList weaponList;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    void setData(ArrayList list) {
        if (list != null) {

            for (int i = 0; i < vec.size(); i++) {
                if (i == 5 || i == 7) {
                    if (i == 5) {
                        JList l = (JList) vec.get(i);
                        ArrayList aL = (ArrayList) list.get(i);
                        for (int x = 0; x < aL.size(); x++) {
                            mdcVec.add(aL.get(x));
                        }
                        l.setListData(mdcVec);
                    } else {
                        JList l = (JList) vec.get(i);
                        ArrayList aL = (ArrayList) list.get(i);
                        for (int x = 0; x < aL.size(); x++) {
                            weapVec.add(aL.get(x));
                        }
                        l.setListData(mdcVec);
                    }
                } else if (i == 6 || i == 8) {
                    JTextArea f = (JTextArea) vec.get(i);
                    f.setText((String) list.get(i));
                } else {
                    JTextField f = (JTextField) vec.get(i);
                    f.setText((String) list.get(i));
                }
            }
        }
    }

    public ArrayList getData() {
        ArrayList list = new ArrayList();
        for (int i = 0; i < vec.size(); i++) {
            if (i == 5 || i == 7) {
                if (i == 5) {
                    ArrayList aL = new ArrayList();
                    for (int x = 0; x < mdcVec.size(); x++) {
                        aL.add(mdcVec.get(x));
                    }
                    list.add(aL);
                } else {                    
                    ArrayList aL = new ArrayList();
                    for (int x = 0; x < weapVec.size(); x++) {
                        aL.add(weapVec.get(x));
                    }
                    list.add(aL);
                }
            } else if (i == 6 || i == 8) {
                JTextArea f = (JTextArea) vec.get(i);
                    list.add(f.getText());
            } else {
                JTextField f = (JTextField) vec.get(i);
                list.add(f.getText());
            }
        }
        return list;
    }
}
